import React from "react";
import { useTranslation } from "react-i18next";
import { Slider } from "../ui/Slider";
import { useSettings } from "../../hooks/useSettings";

/**
 * Microphone sensitivity, mapped onto the voice-activity threshold in the
 * backend. Higher picks up quieter speech and more background noise with it.
 *
 * Lives next to the microphone picker and its level meter, because those three
 * are one decision: which device, does it hear me, and how eagerly.
 */
export const MicSensitivity: React.FC<{ grouped?: boolean }> = ({
  grouped = true,
}) => {
  const { t } = useTranslation();
  const { getSetting, updateSetting } = useSettings();
  // `bindings.ts` is generated by running a debug build and lags behind
  // settings added since; the cast avoids hand-editing a generated file.
  const sensitivity =
    (getSetting("mic_sensitivity" as never) as number | undefined) ?? 0.5;

  return (
    <Slider
      value={sensitivity}
      onChange={(value: number) =>
        updateSetting("mic_sensitivity" as never, value as never)
      }
      min={0}
      max={1}
      label={t("dictationTest.sensitivity")}
      description={t("dictationTest.sensitivityHint")}
      descriptionMode="tooltip"
      grouped={grouped}
      formatValue={(v) => `${Math.round(v * 100)}%`}
    />
  );
};

export default MicSensitivity;
